title: Mac Benedicto # your name (or website title) here
logo: "/images/PP.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Up-and-comer data analyst
  <br><br>
  <a href="https://www.linkedin.com/in/bndc2rymrk/">View My LinkedIn Profile</a> 
  <br><br>
  <a href="https://www.credly.com/badges/de206682-2974-4e2c-a3a7-157606e50827/linked_in_profile">View My Google Data Analytics Certificate</a> 
  
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
