title: Mac Benedicto # your name (or website title) here
logo: "/images/1654751302846.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Up-and-comer data analyst
  <br><br>
  <a href="https://www.linkedin.com/in/bndc2rymrk/">View My LinkedIn Profile</a> 
  
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
